# Week 11 Homework

Write a class that generates fake data.

* Write the code under the py docs ( do NOT remove docs strings)
* Before comitting do a Restart & Run All

Make sure that if a dataframe is passed in, it should not remove any value from it.

In [2]:

class FakeDataGenerator:
    
    def __init__(self, df = None, rows=5):
        """
        This class generates fake data
        
        If data frame is passed in it will add the fake data to it. 
        Otherwise, it will create a new data frame
        
        Parameters:
        -----------
        df: 
          DataFrame default is None
          
        rows:
          If df None, this parameter will be used to create a data frame with `row` lenght
        """
        # code goes under this line. 
        # I will deduct points if any code is written above the comments!
        

        self.df = df
        
        
    def add_random_number(self, column_name, small_value, high_value): # optional: add probabilities 
        """
        adds fake numbers to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df       
    
        
    def add_first_name(self, column_name):
        """
        adds fake first name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df
    
    
    def add_last_name(self, column_name):
        """
        adds fake last name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df
    
    
    def add_email(self, column_name):
        """
        adds fake email to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df
    
    
    def add_phone_number(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df
    
    
    def add_address(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df

In [2]:
import pandas as pd

# Case 1 - existing data frame 
df = pd.DataFrame()
df['product_id'] = [i + 123 for i in range(25)]
df.head()

   product_id
0         123
1         124
2         125
3         126
4         127

In [3]:
fakeGen = FakeDataGenerator(df) # I'm creating instance using existing df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')

,product_id,shipping_address,billing_address,customer_phone
0,123,"230 Jennifer Overpass\nLeehaven, LA 64300",2337 David Expressway Suite 904\nSouth Kylemou...,"151 Anthony Drive Apt. 142\nRamirezborough, AR..."
1,124,"48166 Kelly Harbor\nLake Bradleyview, PA 00915","849 Peterson Lake\nPort Cynthiaberg, OH 58276","623 Jermaine Ville\nShortborough, UT 67471"
2,125,"89254 Jones Loaf Suite 599\nAlbertmouth, RI 03945",Unit 0586 Box 6466\nDPO AP 41626,"8675 Sharon Club Apt. 455\nNew Bonnie, AL 89962"
3,126,"42809 Reed Hill Suite 215\nLake Kennethton, LA...","416 Ryan Mill Apt. 953\nJosephburgh, GA 79978","918 John Villages\nTracyfurt, AZ 87497"
4,127,73978 Mary Harbor Suite 888\nWest Connorcheste...,"17969 Carroll Circles Suite 547\nTamaraton, OH...","80571 Hall Motorway\nPhillipston, ID 69504"
5,128,"2845 Stephanie Shoal\nCarmenchester, MI 37747","86307 Carpenter Track\nRamosberg, MN 83292","1838 Timothy Groves\nPort Patrick, MA 37630"
6,129,"1941 Baker Cliff\nJessicashire, UT 10147",55323 Jeffery Grove Apt. 900\nNorth Christinav...,"87983 Duane Ranch Apt. 284\nSimpsonborough, NH..."
7,130,"316 Sanchez Crossing\nSouth Jasonhaven, KS 58542","6210 Molly Station Apt. 019\nLake Vanessabury,...",USS Ferguson\nFPO AP 28708
8,131,USCGC Austin\nFPO AA 98664,"4525 Smith Lakes\nAndrewburgh, TX 85132","5609 Adam Underpass\nJillberg, VA 28761"
9,132,"22539 Woodward Motorway\nHarmonhaven, HI 46331","34120 Whitehead Lodge\nEast Alexanderstad, MA ...","130 Ashley Fall\nJefferyport, KY 05142"
10,133,"261 Davis Prairie\nDonaldshire, TN 67429","109 Lewis Point\nWest Davidport, WV 76255","91408 Thomas Islands Suite 597\nLindafurt, SD ..."
11,134,"000 Wright Stream\nCynthiaborough, SD 69626","04340 Powell Station\nAmyfurt, ID 53033","664 Ellis Harbors\nNorth Michael, NY 11796"
12,135,"202 Wallace Burgs\nJacksonchester, TX 01247","38233 Spence Mills\nStaffordview, CT 83381",28542 Lauren Stream Apt. 233\nLake Jillianches...
13,136,"9380 Gibson Square\nRodriguezfurt, CA 84637",USCGC Collins\nFPO AE 03817,"410 Bowers Green\nNew Wendy, NM 71232"
14,137,"7134 Williamson Shores\nCannonhaven, CT 61513","2621 Cynthia Isle Apt. 678\nSamuelhaven, AZ 36218","710 Fox Creek Apt. 937\nRebeccamouth, SC 75411"
15,138,"086 Tracie Rest\nPriscillaberg, DE 98651","35479 Black Forge Suite 959\nEricland, NJ 90115","546 Wilson Valley Apt. 489\nEast Ryantown, WY ..."
16,139,"PSC 1499, Box 1135\nAPO AE 81859","16919 Adam Fields\nLake Luis, MN 29311","075 Ralph Mountains Apt. 883\nPort Thomasside,..."
17,140,"PSC 2224, Box 1901\nAPO AP 69069","576 Brown Stravenue Apt. 966\nCodytown, DE 80517","44790 Webb Manor\nWest Kevinton, SD 14479"
18,141,Unit 0511 Box 5100\nDPO AP 99772,"4801 Mays Drive\nSouth Vanessa, TX 02228","3407 Ronnie Camp\nEast Gary, AL 55323"
19,142,"22847 Hart Port Suite 581\nBrockville, KS 96713","942 Victoria Extension\nCrystalborough, MT 09565","19949 Lindsey Plaza\nDanielborough, OR 49059"
20,143,Unit 7053 Box 7063\nDPO AP 17396,"0346 Shawn Coves\nMelaniechester, LA 62064","507 Allison Place\nSouth Miguel, MS 16484"
21,144,"281 Katherine Port Suite 041\nMeadowsmouth, SC...","724 Eugene Oval\nNorth Corymouth, HI 69048","7241 Stacy Hill\nLake Robertburgh, NC 47852"
22,145,"6226 Brown Road\nRalphfort, WI 66292","4019 Kara Gardens Apt. 910\nBrittanymouth, IN ...","802 Porter Isle\nRobertsonville, AL 72896"
23,146,"993 Becker Village\nStevestad, SC 99027","946 Rich Squares\nNew Victoria, MD 09534","2893 Crystal Village\nGreenchester, LA 05384"
24,147,"320 Fisher Circle\nLake Melissa, NE 35956","PSC 5410, Box 8322\nAPO AA 08762","412 Hardy Landing\nNew Nicholasstad, PA 96950"

In [4]:
# Case 2 - no dataframe

fakeGen = FakeDataGenerator() # no df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')
fakeGen.add_random_number('sale_count', 10, 100)

,shipping_address,billing_address,customer_phone,sale_count
0,"07565 Diaz Gardens\nEvansport, WY 04570","908 Katelyn Junction Suite 245\nPort Lisa, DE ...","11207 Cole Place Suite 645\nNorth Juanton, WA ...",84
1,"8638 Townsend Circle\nJenniferborough, WI 55424","304 Atkinson River Suite 918\nNorth Coreyside,...","4624 Jake Tunnel Suite 283\nWest Marcuston, ID...",100
2,"99478 Estes Flats\nNorth Charlesfort, LA 13895","5785 Mathew Parkways Apt. 982\nMonteston, MS 8...","672 Ryan Rapids\nWhitebury, TX 96101",14
3,"66619 Thomas Vista\nReyesshire, CA 15500","9471 Christy Corners\nMillerport, MS 85982","5968 Miguel Point\nHornberg, CA 39143",97
4,"12930 Christy Trace\nArroyoview, MA 90492","7876 Sara Vista\nEast William, UT 33818",6468 Jessica Extension Suite 313\nLake Russell...,59